<a href="https://colab.research.google.com/github/sricheru/python/blob/main/SimplePytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2


4

In [6]:
import torch
import numpy as np


SyntaxError: invalid syntax (<ipython-input-6-68f9d9d76335>, line 2)

In [5]:
list = [[1,2,3,4],[2,3,4,5]]
list

[[1, 2, 3, 4], [2, 3, 4, 5]]

In [13]:
import torch
import numpy as np
np1 = np.random.rand(3,4)
np1

array([[0.36196971, 0.19543267, 0.71581602, 0.9154972 ],
       [0.20408621, 0.64849163, 0.60837076, 0.21654499],
       [0.35391773, 0.53651941, 0.7026255 , 0.33983925]])

In [15]:
tesnor = torch.randn(3,4)
tesnor

tensor([[ 0.9971,  1.2185,  0.2633, -0.5193],
        [ 1.0675,  1.2269, -1.4549, -0.6059],
        [ 0.1432,  0.5832, -0.2788,  1.2879]])

In [21]:
tensor = torch.zeros(4,2,3)
tensor


tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])